- name: Deploy base master services
  hosts: civmaster
  remote_user: root
  become: yes

  vars:
    mysql_root_password: classic

  tasks:
    - name: Remove mysql-client
      apt:
        name: mysql-client
        state: absent
        update_cache: yes
        cache_valid_time: 86400

    - name: Remove mysql-server
      apt:
        name: mysql-server
        state: absent
        update_cache: yes
        cache_valid_time: 86400

    - name: Install mariadb client
      apt:
        name: mariadb-client
        state: present
        update_cache: yes
        cache_valid_time: 86400

    - name: Install mariadb server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes
        cache_valid_time: 86400

    - name: Install mysql py3 bindings
      apt:
        name: python-pymysql
        state: present
        update_cache: yes
        cache_valid_time: 86400

    - name: Start the MySQL service
      service: name=mysql state=started enabled=true

    - name: copy .my.cnf file with root password credentials
      template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600


    - name: update mysql root password for all root accounts
      mysql_user: name=root host=localhost password={{ mysql_root_password }} check_implicit_admin=yes

    # 'localhost' needs to be the last item for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: update mysql root password for all root accounts
      mysql_user:
        name=root host={{ item }} password={{ mysql_root_password }} check_implicit_admin=yes
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: delete anonymous MySQL server user for $server_hostname
      action: mysql_user user="" host="{{ ansible_host }}" state="absent"

    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent
