- name: Deploy minecraft plugins
  hosts: civservers
  become_user: mc
  become: yes

  vars:
    plugins:
      - { user: CivClassic, plugin_name: TradePlus, build_system: "mvn" }
      - { user: CivClassic, plugin_name: WorldBorder, build_system: "mvn" }
      - { user: CivClassic, plugin_name: CivModCore, build_system: "mvn" }
      - { user: CivClassic, plugin_name: NameLayer, build_system: "mvn" }
      - { user: CivClassic, plugin_name: Citadel, build_system: "mvn" }
      - { user: CivClassic, plugin_name: JukeAlert, build_system: "mvn" }
      - { user: CivClassic, plugin_name: ItemExchange, build_system: "mvn" }
      - { user: CivClassic, plugin_name: ExilePearl, build_system: "mvn" }
      - { user: CivClassic, plugin_name: FactoryMod, build_system: "mvn" }
      - { user: CivClassic, plugin_name: Bastion, build_system: "mvn" }
      - { user: CivClassic, plugin_name: RealisticBiomes, build_system: "mvn" }
      - { user: CivClassic, plugin_name: CivChat2, build_system: "mvn" }
      - { user: CivClassic, plugin_name: BanStick, build_system: "mvn" }
      - { user: CivClassic, plugin_name: CivDuties, build_system: "mvn" }
      - { user: CivClassic, plugin_name: CivSpy, build_system: "mvn" }
      - { user: CivClassic, plugin_name: EssenceGlue, build_system: "mvn" }
      - { user: CivClassic, plugin_name: Finale, build_system: "mvn" }
      - { user: CivClassic, plugin_name: HiddenOre, build_system: "mvn" }
      - { user: CivClassic, plugin_name: NameColors, build_system: "mvn" }
      - { user: CivClassic, plugin_name: OldEnchanting, build_system: "mvn" }
      - { user: CivClassic, plugin_name: Orebfuscator, build_system: "mvn" }
      - { user: CivClassic, plugin_name: RailSwitch, build_system: "mvn" }
      - { user: CivClassic, plugin_name: RandomSpawn, build_system: "mvn" }
      - { user: CivClassic, plugin_name: RealisticBiomes, build_system: "mvn" }
      - { user: CivClassic, plugin_name: SimpleAdminHacks, build_system: "mvn" }


  tasks:
    - name: Server plugin folder should exist.
      file:
        path: "/home/mc/projects/"
        state: directory
        recurse: yes
        owner: mc
        group: mc
        mode: 0755

    - name: Check if checkout directories already exist.
      stat:
        path: "/home/mc/projects/{{ item.plugin_name }}"
      register: repo_stats
      with_items: "{{plugins}}"

    - name: Checkout civclassic github plugins
      git:
        repo: "git@github.com:{{ item.item.user }}/{{ item.item.plugin_name }}.git"
        dest: "/home/mc/static_plugins/{{ item.item.plugin_name }}"
        accept_hostkey: yes
      when: not item.stat.exists
      with_items: "{{repo_stats.results}}"

    - name: Build civclassic plugins (mvn)
      shell:
        executable: "/bin/bash"
        cmd : "mvn package -DskipTests -Dmaven.test.skip=true -Dmaven.wagon.http.ssl.allowall=true"
        chdir: "/home/mc/projects/{{ item.plugin_name }}"
      when: item.build_system == "mvn"
      with_items: "{{plugins}}"

    - name: Build civclassic plugins (gradle)
      shell:
        executable: "/bin/bash"
        cmd: "./gradlew build -x test"
        chdir: "/home/mc/projects/{{ item.plugin_name }}"
      when: item.build_system == "gradle"
      with_items: "{{plugins}}"
