- name: Deploy minecraft plugins
  hosts: civservers
  become_user: mc
  become: yes

  tasks:
    - name: Server plugin folder should exist.
      file:
        path: "/home/mc/static_plugins/"
        state: directory
        recurse: yes
        owner: mc
        group: mc
        mode: 0755

    - name: Register output
      stat:
        path: "/home/mc/static_plugins/{{ item.plugin_name }}"
      register: repo_stats
      with_items:
        - { user: dmulloy2, plugin_name: ProtocolLib }
        - { user: Warren1001, plugin_name: attributehider }
        - { user: SpraxDev, plugin_name: BetterChairs }
        - { user: DieReicheErethons, plugin_name: Brewery }
        - { user: SpigotMC, plugin_name: BungeeCord }
        - { user: lucko, plugin_name: BungeeGuard }
        - { user: Byteflux, plugin_name: CombatTagPlus }
        - { user: filoghost, plugin_name: HolographicDisplays }
        - { user: lucko, plugin_name: LuckPerms }
        - { user: EngineHub, plugin_name: WorldEdit }
        - { user: MilkBowl, plugin_name: Vault }
        - { user: MyzelYam, plugin_name: SuperVanish }
        - { user: NuVotifier, plugin_name: NuVotifier }

    - name: Checkout non-civclassic github plugins
      git:
        repo: "git@github.com:{{ item.user }}/{{ item.plugin_name }}.git"
        dest: "/home/mc/static_plugins/{{ item.plugin_name }}"
        accept_hostkey: yes
      when: not item.stat.exists
      with_items: "{{ repo_stats.results }}"
