- name: Deploy base master services
  hosts: civmaster
  become_user: mc
  become: yes

  vars:
    git_user_name: psygate

  tasks:
    - name: Copy github credentials private key
      copy:
        src: '/vagrant/credentials/{{ item.file_name }}'
        dest: '/home/mc/.ssh/{{ item.file_name }}'
        owner: mc
        group: mc
        mode: '0600'
      with_items:
        - { file_name: github.pub, permissions: '0600' }
        - { file_name: github, permissions: '0644' }

    - name: copy ssh config files
      template: src=templates/mc/ssh_config.j2 dest=/home/mc/.ssh/config owner=mc group=mc mode=0600

    - name: Setup project folder
      file:
        path: /home/mc/projects
        state: directory
        recurse: yes
        owner: mc

    - name: Register output
      stat:
        path: "/home/mc/static_plugins/{{ item.plugin_name }}"
      register: repo_stats
      with_items:
        - { user: CivClassic, plugin_name: TradePlus }
        - { user: CivClassic, plugin_name: WorldBorder }
        - { user: CivClassic, plugin_name: CivModCore }
        - { user: CivClassic, plugin_name: NameLayer }
        - { user: CivClassic, plugin_name: Citadel }
        - { user: CivClassic, plugin_name: JukeAlert }
        - { user: CivClassic, plugin_name: ItemExchange }
        - { user: CivClassic, plugin_name: ExilePearl }
        - { user: CivClassic, plugin_name: FactoryMod }
        - { user: CivClassic, plugin_name: Bastion }
        - { user: CivClassic, plugin_name: RealisticBiomes }
        - { user: CivClassic, plugin_name: CivChat2 }
        - { user: CivClassic, plugin_name: BanStick }
        - { user: CivClassic, plugin_name: CivDuties }
        - { user: CivClassic, plugin_name: CivSpy }
        - { user: CivClassic, plugin_name: EssenceGlue }
        - { user: CivClassic, plugin_name: Finale }
        - { user: CivClassic, plugin_name: HiddenOre }
        - { user: CivClassic, plugin_name: NameColors }
        - { user: CivClassic, plugin_name: OldEnchanting }
        - { user: CivClassic, plugin_name: Orebfuscator }
        - { user: CivClassic, plugin_name: RailSwitch }
        - { user: CivClassic, plugin_name: RandomSpawn }
        - { user: CivClassic, plugin_name: RealisticBiomes }
        - { user: CivClassic, plugin_name: SimpleAdminHacks }

    - name: Checkout civclassic github plugins
      git:
        repo: "git@github.com:{{ item.user }}/{{ item.plugin_name }}.git"
        dest: "/home/mc/static_plugins/{{ item.plugin_name }}"
        accept_hostkey: yes
      when: not item.stat.exists
      with_items: "{{ repo_stats.results }}"
